#!/usr/bin/env python3
import subprocess
import os

DEPENDENCIES = ['pytest']

VENV_FOLDER = ".venv"
VENV_INTERPRETER = ".venv/bin/python"


def setup_step(descriptor: str):
    cols = os.get_terminal_size().columns
    _descriptors = descriptor.split("\n")
    def inner(func):
        def wrapper(*args, **kwargs):
            print("*"*cols)
            for descriptor in _descriptors:
                lpad = ((cols - len(descriptor)) // 2) - 2
                rpad = cols - lpad - len(descriptor) - 2
                print("*" + " "*lpad + descriptor + " "*rpad + "*")
            print("*"*cols)
            func(*args, **kwargs)
            # print("*" + " "*lpad + descriptor + " "*rpad + "*")

        return wrapper
    return inner


@setup_step("Set up Python virtual environment")
def setup_venv():
    p1 = subprocess.Popen(["python3", "-m", "venv", VENV_FOLDER], stdout=subprocess.PIPE)
    out, err = p1.communicate()
    print(out.decode('utf-8'))


@setup_step(f"Install dependencies to virtual environment: \n{'\n'.join(DEPENDENCIES)}")
def install_dependencies():
    for dep in DEPENDENCIES:
        p2 = subprocess.Popen([VENV_INTERPRETER, "-m", "pip", "install", dep], stdout=subprocess.PIPE)
        out, err = p2.communicate()
        print(out.decode('utf-8'))


@setup_step("Set up PyDotON (editable) in")
def install_pydoton():
    p3 = subprocess.Popen([VENV_INTERPRETER, "-m", "pip", "install", "-e", "."], stdout=subprocess.PIPE)
    out, err = p3.communicate()
    print(out.decode('utf-8'))


@setup_step("PyDotON setup done")
def installation_done():
    pass


def main():
    setup_venv()
    install_dependencies()
    install_pydoton()
    installation_done()


if __name__ == "__main__":
    main()